### ISSUE TITLE
Aren't 'kin', 'namako', 'oko' pu words?

### ISSUE THREAD

**Issue by formicant** [lipu-linku/jasima#3]
The words _kin_, _namako_, and _oko_, while considered synonyms of other words, do exist in _pu_.

Shouldn't the `book` property of these words be `pu`?

**Comment by AcipenserSturio** [comment]
At the time of making Linku, it was important to simplify the classification that was getting too messy. We decided to include the synonyms in the "ku suli" bunch because

(a) otherwise "17 ku suli" as advertised no longer shows up as such

(b) the description of kin and namako as "synonyms" never really reflected real usage: people who wanted to stick to pu just didn't use them, and people who wanted to use them didn't use them as described in pu. (oko is more arguable in that regard)

(c) tonsi is also a pu word. It shows up... in the German translation only

(d) in fact all ku sulis are pu, cause they show up in pu Esperanto

To avoid this mess, we just lumped them the least wrong way.

I am however considering changing that in the future (by adding like an intermediate "sort of in pu, with an asterisk" category).
